import{a as f,S as L}from"./assets/vendor-84b78643.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function v(r){try{return await f.get(r)}catch(t){throw new Error(t)}}const g=document.createDocumentFragment(),w=document.querySelector(".gallery");function S(r){r.forEach(({webformatURL:t,largeImageURL:a,tags:l,likes:e,views:s,comments:n,downloads:h})=>{const u=document.createElement("li");u.classList.add("gallery-items"),u.insertAdjacentHTML("beforeend",`<a class='gallery-link' href='${a}'>
        <img class='gallery-image' src='${t}' alt='${l}' />
        <ul class='gallery-ul'>
          <li class='gallery-item'><h3 class='gallery-title'>Likes</h3><p class='gallery-value'>${e}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Views</h3><p class='gallery-value'>${s}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Comments</h3><p class='gallery-value'>${n}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Downloads</h3><p class='gallery-value'>${h}</p></li>
        </ul>
      </a>`),g.appendChild(u)}),w.appendChild(g)}const b=document.querySelector(".form"),q=document.querySelector(".gallery"),d=document.querySelector(".loader"),i=document.querySelector(".load-more"),m="https://pixabay.com/api/?",o={key:"42159131-e2480a23f0f5c24b1f6f03d93",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1};let y=0;const $={overlayOpacity:.8,captionsData:"alt",captionDelay:250},E=new L(".gallery a",$);b.addEventListener("submit",r=>{r.preventDefault(),q.innerHTML="",o.page=1;const t=document.querySelector("input"),a=t.value.trim();if(!a)iziToast.warning({message:"You forgot to enter your details"});else{c(),o.q=a;const l=m+new URLSearchParams(o);p(l)}t.value=""});const p=async(r,t)=>{await v(r).then(({data:a})=>{const l=a.hits;y=a.totalHits,l.length>0?(O(l),window.scrollBy({top:t,behavior:"smooth"})):(c(),iziToast.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"#f83d04"}))}).catch(a=>{iziToast.warning({message:a})})};function O(r){S(r),c(),i.classList.remove("hide"),E.refresh(),P()}i.addEventListener("click",()=>{o.page+=1;const r=m+new URLSearchParams(o);c(),i.classList.add("hide");const t=document.querySelector(".gallery-items").getBoundingClientRect().height*2+26;p(r,t)});function c(){d.classList.contains("hide")?d.classList.remove("hide"):(d.classList.add("hide"),i.classList.add("hide"))}function P(){y<o.page*o.per_page&&!i.classList.contains("hide")&&(i.classList.add("hide"),iziToast.info({message:"We're sorry, but you've reached the end of search results."}))}
//# sourceMappingURL=commonHelpers.js.map
